///********************************************************************************************************************************
///The code on this page is generated by the code generator, do not manually modify.
///CodeGenerator: Megumin.CSCodeGenerator.  Version: 1.0.2
///CodeGenericBy: Megumin.AI.BehaviorTree.Editor.NodeGenerator
///CodeGenericSourceFilePath: Packages/com.megumin.ai.behaviortree/Editor/Generator/NodeGeneraotr.asset
///********************************************************************************************************************************

using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using UnityEngine;

namespace Megumin.AI.BehaviorTree
{
    [DisplayName("PlayerPrefs_DeleteKey")]
    [Category("UnityEngine/PlayerPrefs")]
    [AddComponentMenu("DeleteKey(String)")]
    [CodeGeneratorInfo(Name = "Megumin.CSCodeGenerator")]
    public sealed class PlayerPrefs_DeleteKey_String_Node : BTActionNode
    {
        [Space]
        public Megumin.Binding.RefVar_String key;

        protected override Status OnTick(BTNode from, object options = null)
        {
            UnityEngine.PlayerPrefs.DeleteKey(key);
            return Status.Succeeded;
        }
    }
}




