///********************************************************************************************************************************
///The code on this page is generated by the code generator, do not manually modify.
///CodeGenerator: Megumin.CSCodeGenerator.  Version: 1.0.2
///CodeGenericBy: Megumin.AI.BehaviorTree.Editor.NodeGenerator
///CodeGenericSourceFilePath: Packages/com.megumin.ai.behaviortree/Editor/Generator/NodeGeneraotr.asset
///********************************************************************************************************************************

using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using UnityEngine;

namespace Megumin.AI.BehaviorTree
{
    [DisplayName("Physics_Simulate")]
    [Category("UnityEngine/Physics")]
    [AddComponentMenu("Simulate(Single)")]
    [CodeGeneratorInfo(Name = "Megumin.CSCodeGenerator")]
    public sealed class Physics_Simulate_Single_Node : BTActionNode
    {
        [Space]
        public Megumin.Binding.RefVar_Float step;

        protected override Status OnTick(BTNode from, object options = null)
        {
            UnityEngine.Physics.Simulate(step);
            return Status.Succeeded;
        }
    }
}




