///********************************************************************************************************************************
///The code on this page is generated by the code generator, do not manually modify.
///CodeGenerator: Megumin.CSCodeGenerator.  Version: 1.0.2
///CodeGenericBy: Megumin.AI.BehaviorTree.Editor.NodeGenerator
///CodeGenericSourceFilePath: Packages/com.megumin.ai.behaviortree/Editor/Generator/NodeGeneraotr.asset
///********************************************************************************************************************************

using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using UnityEngine;

namespace Megumin.AI.BehaviorTree
{
    [Icon("BoxCollider2D Icon")]
    [DisplayName("Set_BoxCollider2D_autoTiling")]
    [Category("UnityEngine/BoxCollider2D")]
    [AddComponentMenu("Set_autoTiling")]
    [CodeGeneratorInfo(Name = "Megumin.CSCodeGenerator")]
    public sealed class BoxCollider2D_autoTiling_Set_Node : BTActionNode<UnityEngine.BoxCollider2D>
    {
        [Space]
        public Megumin.Binding.RefVar_Bool Value;

        protected override Status OnTick(BTNode from, object options = null)
        {
            ((UnityEngine.BoxCollider2D)MyAgent).autoTiling = Value;
            return Status.Succeeded;
        }

    }
}




