///********************************************************************************************************************************
///The code on this page is generated by the code generator, do not manually modify.
///CodeGenerator: Megumin.CSCodeGenerator.  Version: 1.0.2
///CodeGenericBy: Megumin.AI.BehaviorTree.Editor.NodeGenerator
///CodeGenericSourceFilePath: Packages/com.megumin.ai.behaviortree/Editor/Generator/NodeGeneraotr.asset
///********************************************************************************************************************************

using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using UnityEngine;

namespace Megumin.AI.BehaviorTree
{
    [Icon("BoxCollider2D Icon")]
    [DisplayName("BoxCollider2D_edgeRadius")]
    [Category("UnityEngine/BoxCollider2D")]
    [AddComponentMenu("edgeRadius")]
    [CodeGeneratorInfo(Name = "Megumin.CSCodeGenerator")]
    public sealed class BoxCollider2D_edgeRadius_Decorator : CompareDecorator<UnityEngine.BoxCollider2D, float>
    {
        [Space]
        public Megumin.Binding.RefVar_Float CompareTo;

        [Space]
        public Megumin.Binding.RefVar_Float SaveValueTo;

        public override float GetResult()
        {
            var result = ((UnityEngine.BoxCollider2D)MyAgent).edgeRadius;

            if (SaveValueTo != null)
            {
                SaveValueTo.Value = result;
            }

            return result;
        }

        public override float GetCompareTo()
        {
            return CompareTo;
        }

    }
}




