///********************************************************************************************************************************
///The code on this page is generated by the code generator, do not manually modify.
///CodeGenerator: Megumin.CSCodeGenerator.  Version: 1.0.2
///CodeGenericBy: Megumin.AI.BehaviorTree.Editor.NodeGenerator
///CodeGenericSourceFilePath: Packages/com.megumin.ai.behaviortree/Editor/Generator/NodeGeneraotr.asset
///********************************************************************************************************************************

using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using UnityEngine;

namespace Megumin.AI.BehaviorTree
{
    [DisplayName("Vector3_Set")]
    [Category("UnityEngine/Vector3")]
    [AddComponentMenu("Set(Single, Single, Single)")]
    [CodeGeneratorInfo(Name = "Megumin.CSCodeGenerator")]
    public sealed class Vector3_Set_Single_Single_Single_Node : BTActionNode
    {
        [Space]
        public Megumin.Binding.RefVar_Vector3 MyAgent;

        [Space]
        public Megumin.Binding.RefVar_Float newX;
        public Megumin.Binding.RefVar_Float newY;
        public Megumin.Binding.RefVar_Float newZ;

        protected override Status OnTick(BTNode from, object options = null)
        {
            ((UnityEngine.Vector3)MyAgent).Set(newX, newY, newZ);
            return Status.Succeeded;
        }
    }
}




